# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fc895ef4120734404ac3284b58367c1bf4c7df4f8e02d1a113ed6d2a035db685a4ef53d3193ee5f6f4d2764dfd4e5359e0eaa9151b19bcf7bcdde183f2f5e479

test:
  secret_key_base: d94680a06d873c639b356ea2d84afeb4cb40901fc3d2b2ad94eb975eade86eec2debc934d296ac41353ffdb7a4ce8eb8d1a1e0ada32d7ed4f7cb595e9f5dcb69

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
